version: '3.7'

networks:
    twitter-test-network:
        driver: bridge

services:

#twitter-test-db
    twitter-test-db:
        image: mysql:5.7
        container_name: ${DB_HOST:-twitter-test-db}
        restart: always
        ports:
            - "${DB_PORT:-12006}:3306"
        environment:
            MYSQL_DATABASE: ${DB_DATABASE:-twitter_test}
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root}
            TZ: ${TZ:-Asia/Taipei}
        command: [
            "--character-set-server=utf8mb4",
            "--collation-server=utf8mb4_general_ci",
            "--innodb-use-native-aio=0",
            "--server-id=1",
            "--log_bin=ON",
            "--default-authentication-plugin=mysql_native_password"
        ]
        volumes:
            - ./data/mysql:/var/lib/mysql
        networks:
            - twitter-test-network

#twitter-test-redis
    twitter-test-redis:
        build:
            context: .
            dockerfile: ./dockerfile/redis.dockerfile
        image: danielhuang030/twitter-test-redis:0.0.1
        container_name: ${REDIS_HOST:-twitter-test-redis}
        restart: always
        ports:
            - "${REDIS_PORT:-12009}:6379"
        volumes:
            - ./data/redis:/data
            - ./conf/redis/redis.conf:/usr/local/etc/redis/redis.conf
        networks:
            - twitter-test-network

#phpMyAdmin
    pma:
        image: phpmyadmin/phpmyadmin:latest
        container_name: twitter-test-pma
        restart: always
        volumes:
            - type: bind
              source: ./conf/phpMyAdmin/config.user.inc.php
              target: /etc/phpmyadmin/config.user.inc.php
        ports:
            - "${PMA_PORT:-12010}:80"
        environment:
            SESSION_TIMEOUT: ${PMA_SESSION_TIMEOUT:-86400}
            PMA_HOST: ${DB_HOST:-twitter-test-db}
        networks:
            - twitter-test-network
        depends_on:
            - ${DB_HOST:-twitter-test-db}

#phpRedisAdmin
    pra:
        image: erikdubbelboer/phpredisadmin:latest
        container_name: twitter-test-pra
        restart: always
        ports:
            - "${PRA_PORT:-12020}:80"
        environment:
            REDIS_1_HOST: ${REDIS_HOST:-twitter-test-redis}
            REDIS_1_NAME: ${REDIS_HOST:-twitter-test-redis}
        networks:
            - twitter-test-network
        depends_on:
            - ${REDIS_HOST:-twitter-test-redis}

#twitter-test
    twitter-test:
        build:
            context: .
            dockerfile: ./dockerfile/app.dockerfile
        image: danielhuang030/twitter-test:0.0.6
        container_name: ${APP:-twitter-test-app}
        restart: always
        volumes:
            - ../:/var/www/html/
            - type: bind
              source: ./conf/supervisord/supervisord.conf
              target: /etc/supervisord.conf
            - type: bind
              source: ./conf/php/php.ini
              target: /usr/local/etc/php/conf.d/php-custom.ini
            # - type: bind
            #   source: ./conf/cron/root
            #   target: /etc/crontabs/root
        ports:
            - "${SUPERVISORD_PORT:-12008}:9001"
        networks:
            - twitter-test-network
        depends_on:
            - ${DB_HOST:-twitter-test-db}
            - ${REDIS_HOST:-twitter-test-redis}

#twitter-test-soketi
    twitter-test-soketi:
        image: 'quay.io/soketi/soketi:latest-16-alpine'
        container_name: twitter-test-soketi
        restart: always
        environment:
            DEBUG: '1'
            DEFAULT_APP_ID: ${SOKETI_APP_ID:-app-id}
            DEFAULT_APP_KEY: ${SOKETI_APP_KEY:-app-key}
            DEFAULT_APP_SECRET: ${SOKETI_APP_SECRET:-app-secret}
            PORT: 6001
        ports:
            - '${WEBSOCKET_PORT:-12001}:6001'
        networks:
            - twitter-test-network

#twitter-test-web-server
    twitter-test-web-server:
        image: nginx:alpine
        container_name: twitter-test-web-server
        restart: always
        volumes:
            - ../:/var/www/html
            - ./log/nginx/:/var/log/nginx
            - type: bind
              source: ./conf/nginx/default.conf
              target: /etc/nginx/conf.d/default.conf
        ports:
            - "${WEB_PORT:-12000}:80"
        networks:
            - twitter-test-network
